### ISSUE TITLE
Website doesn't generate images

### ISSUE THREAD

**Issue by LOLZCa** [smhussain5/DALLE3-Generator#1]
The website hasn't been generating new images
Can you fix this problem?

**Comment by smhussain5** [comment]
Hey! Thanks for notifying me. I added more credits because it appears people have been using it, which is nice. Issue should be resolved now 🤞

**Comment by LOLZCa** [comment]
Will there be an option for “no illustration style” for more prompt creativity?
Sometimes people wanna create their own illustration style without the one provided
