### ISSUE TITLE
The website isn't loading images again

### ISSUE THREAD

**Issue by LOLZCa** [smhussain5/DALLE3-Generator#2]
Maybe you should change the API code every once and a while

**Comment by smhussain5** [comment]
I see. Was it working after I resolved the first issue?

**Comment by LOLZCa** [comment]
Yeah but now it’s really slow
On a side note, will there ever be a “No Style” option on the website? It’s so people can be free to use any style they want

**Comment by smhussain5** [comment]
That's a good idea. I'll look into it for future refactoring. For now, I wouldn't recommend using it until it's refactored. Thank you in advance! :-)

**Comment by smhussain5** [comment]
Hello! Refactored the site. You will need to use your own API key from OpenAI. Also custom styles have been added. Thanks!
